name: 'Manual DRYWALL-WALL-DETECTOR Cloud Run Build and Deploy'

on:
  # Manual trigger for the Cloud Run deployment
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - QA

jobs:
  build-and-deploy:
    name: 'Build, Push, and Deploy to Cloud Run'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: wall-detector

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ github.event.inputs.environment == 'QA' && vars.WIF_PROVIDER_QA || vars.WIF_PROVIDER_DEV }}
          service_account: ${{ github.event.inputs.environment == 'QA' && vars.SERVICE_ACCOUNT_QA || vars.SERVICE_ACCOUNT_DEV }}
      
      # Set up GCP Project ID 
      - name: "Set GCP Project ID"
        run: |
          if [ "${{ github.event.inputs.environment }}" == "QA" ]; then
            echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID_QA }}" >> $GITHUB_ENV
          else
            echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID_DEV }}" >> $GITHUB_ENV
          fi

      # Set up Google Cloud SDK
      - name: 'Set up Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          # export_default_credentials: true

      
      # Set model paths based on environment
      - name: "Set Model Paths"
        run: |
          if [ "${{ github.event.inputs.environment }}" == "QA" ]; then
            echo "MODEL_BUCKET=${{ vars.MODEL_BUCKET_QA }}" >> $GITHUB_ENV
            echo "FINETUNED_MODEL_PATH=${{ vars.FINETUNED_MODEL_PATH_QA }}" >> $GITHUB_ENV
            echo "BASE_MODEL_PATH=${{ vars.BASE_MODEL_PATH_QA }}" >> $GITHUB_ENV
          else
            echo "MODEL_BUCKET=${{ vars.MODEL_BUCKET_DEV }}" >> $GITHUB_ENV
            echo "FINETUNED_MODEL_PATH=${{ vars.FINETUNED_MODEL_PATH_DEV }}" >> $GITHUB_ENV
            echo "BASE_MODEL_PATH=${{ vars.BASE_MODEL_PATH_DEV }}" >> $GITHUB_ENV
          fi

      # Download model weights from GCS before Docker build
      - name: 'Download Model Folders'
        run: |
          mkdir -p models

          gsutil -m cp -r \
            gs://${{ env.MODEL_BUCKET }}/${{ env.FINETUNED_MODEL_PATH }} \
            models/

          gsutil -m cp -r \
            gs://${{ env.MODEL_BUCKET }}/${{ env.BASE_MODEL_PATH }} \
            models/

          echo "Downloaded model folders:"
          find models

      # Cleanup Docker cache before build
      - name: 'Cleanup Docker'
        run: |
          docker system prune -a -f --volumes
          docker builder prune -a -f

      # Build the Docker image for Cloud Run
      - name: 'Build Docker Image'
        run: |
          docker build \
            -t gcr.io/${{ env.GCP_PROJECT_ID }}/wall-detector \
            .

      # Docker Authentication with Artifact Registry
      - name: Docker Authentication
        run: |
         gcloud auth configure-docker gcr.io --quiet
 

      # Set up VPC Access Connector
      - name: "Set VPC Access Connector"
        run: |
          if [ "${{ github.event.inputs.environment }}" == "QA" ]; then
            echo "VPC_ACCESS_CONNECTOR=${{ vars.VPC_ACCESS_CONNECTOR_QA }}" >> $GITHUB_ENV
          else
            echo "VPC_ACCESS_CONNECTOR=${{ vars.VPC_ACCESS_CONNECTOR_DEV }}" >> $GITHUB_ENV
          fi

      # Push the Docker image to Google Container Registry
      - name: 'Push Docker Image to GCR'
        run: |
          docker push \
           gcr.io/${{ env.GCP_PROJECT_ID }}/wall-detector

      # Deploy to Cloud Run
      - name: 'Deploy to Cloud Run'
        run: |
           gcloud run deploy wall-detector \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/wall-detector \
            --platform managed \
            --region us-central1 \
            --project ${{ env.GCP_PROJECT_ID }} \
            --service-account ${{ github.event.inputs.environment == 'QA' && vars.SERVICE_ACCOUNT_QA || vars.SERVICE_ACCOUNT_DEV }} \
            --cpu 8 \
            --memory 32Gi \
            --min-instances 1 \
            --max-instances 100 \
            --concurrency 1 \
            --execution-environment gen2 \
            --timeout 1800 \
            --ingress internal \
            --vpc-connector ${{ env.VPC_ACCESS_CONNECTOR }} \
            --vpc-egress all-traffic \
            --no-allow-unauthenticated
